# Generated by Django 4.0.3 on 2022-03-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
