# Generated by Django 4.0.3 on 2022-03-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'рецепт', 'verbose_name_plural': 'рецепты'},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(blank=True, verbose_name='Калорийность, ккал'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес, г'),
        ),
        migrations.CreateModel(
            name='Dishitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=200, verbose_name='Наименование')),
                ('amount', models.CharField(blank=True, max_length=10, verbose_name='Количество')),
                ('measurement_unit', models.CharField(blank=True, max_length=10, verbose_name='Единица измерения')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodplanapp.dish', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
            },
        ),
    ]
