# Generated by Django 4.0.3 on 2022-03-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0002_alter_dish_options_remove_dish_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='guide',
            field=models.TextField(blank=True, verbose_name='Инструкция'),
        ),
    ]
