# Generated by Django 4.0.3 on 2022-03-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0002_delete_user'),
        ('foodplanapp', '0004_alter_dish_calories'),
    ]

    operations = [
    ]
