# Generated by Django 4.0.3 on 2022-03-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0006_dish_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
