# Generated by Django 4.0.3 on 2022-03-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0007_alter_dish_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='start_price',
        ),
        migrations.AddField(
            model_name='order',
            name='menu_type',
            field=models.CharField(choices=[('classic', 'Классическое меню'), ('low_calorie', 'Низкокалорийное меню'), ('vegan', 'Вегетарианское меню'), ('keto', 'Кето меню')], default='classic', max_length=100, verbose_name='Тип меню'),
        ),
        migrations.AddField(
            model_name='price',
            name='classic_menu',
            field=models.IntegerField(default=100, verbose_name='Классическое меню, руб/мес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='keto_menu',
            field=models.IntegerField(default=100, verbose_name='Кето меню, руб/мес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='low_calorie_menu',
            field=models.IntegerField(default=100, verbose_name='Низкокалорийное меню, руб/мес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='vegan_menu',
            field=models.IntegerField(default=100, verbose_name='Вегетарианское меню, руб/мес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='allergy',
            field=models.IntegerField(verbose_name='Доплата за гипоаллергенное меню, руб'),
        ),
        migrations.AlterField(
            model_name='price',
            name='meal',
            field=models.IntegerField(verbose_name='Доплата за каждый прием пищи, руб'),
        ),
        migrations.AlterField(
            model_name='price',
            name='new_year_menu',
            field=models.IntegerField(verbose_name='Доплата за новогоднее меню, руб'),
        ),
        migrations.AlterField(
            model_name='price',
            name='promo_code',
            field=models.IntegerField(verbose_name='Скидка за промокод, руб'),
        ),
    ]
