# Generated by Django 4.0.3 on 2022-03-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0008_remove_price_start_price_order_menu_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='allergy1',
            field=models.BooleanField(default=False, verbose_name='Аллергия 1'),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergy2',
            field=models.BooleanField(default=False, verbose_name='Аллергия 2'),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergy3',
            field=models.BooleanField(default=False, verbose_name='Аллергия 3'),
        ),
        migrations.AddField(
            model_name='dish',
            name='menu_type',
            field=models.CharField(choices=[('classic', 'Классическое меню'), ('low_calorie', 'Низкокалорийное меню'), ('vegan', 'Вегетарианское меню'), ('keto', 'Кето меню')], default='classic', max_length=100, verbose_name='Тип меню'),
        ),
    ]
