# Generated by Django 4.0.3 on 2022-03-18 11:57
import random

from django.db import migrations


class Migration(migrations.Migration):
    def set_allergy_and_menutype_for_dishes(apps, schema_editor):
        menu_types = [
            "classic",
            "low_calorie",
            "vegan",
            "keto",
        ]
        allergy = [True, False]

        Dishes = apps.get_model("foodplanapp", "Dish")
        dishes_set = Dishes.objects.all()
        for dish in dishes_set.iterator():
            dish.menu_type = random.choice(menu_types)
            dish.allergy1 = random.choice(allergy)
            dish.allergy2 = random.choice(allergy)
            dish.allergy3 = random.choice(allergy)
            dish.save()

    dependencies = [
        (
            "foodplanapp",
            "0009_dish_allergy1_dish_allergy2_dish_allergy3_and_more",
        ),
    ]

    operations = [migrations.RunPython(set_allergy_and_menutype_for_dishes)]
