# Generated by Django 4.0.3 on 2022-03-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0011_alter_dish_menu_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'аллергия',
                'verbose_name_plural': 'аллергии',
            },
        ),
        migrations.RemoveField(
            model_name='dish',
            name='allergy1',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='allergy2',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='allergy3',
        ),
        migrations.AddField(
            model_name='dish',
            name='allergies',
            field=models.ManyToManyField(related_name='dishes', to='foodplanapp.allergies'),
        ),
    ]
