# Generated by Django 4.0.3 on 2022-03-20 09:17

import random

from django.db import migrations


class Migration(migrations.Migration):
    def set_allergy_for_dishes(apps, schema_editor):
        allergies = [
            "Рыба и морепродукты",
            "Мясо",
            "Зерновые",
            "Продукты пчеловодства",
            "Орехи и бобовые",
            "Молочные продукты",
        ]

        Allergies = apps.get_model("foodplanapp", "Allergies")
        Dish = apps.get_model("foodplanapp", "Dish")

        for allergie in allergies:
            Allergies.objects.get_or_create(name=allergie)

        dishes_set = Dish.objects.all()
        all_allergies = Allergies.objects.all()
        for dish in dishes_set.iterator():
            for _ in range(0, 3):
                dish.allergies.add(random.choice(all_allergies))
                dish.save()

    dependencies = [
        (
            "foodplanapp",
            "0012_allergies_remove_dish_allergy1_remove_dish_allergy2_and_more",
        ),
    ]

    operations = [migrations.RunPython(set_allergy_for_dishes)]
