# Generated by Django 4.0.3 on 2022-03-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0013_auto_20220320_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='allergies',
            field=models.ManyToManyField(related_name='orders', to='foodplanapp.allergies'),
        ),
    ]
