# Generated by Django 4.0.3 on 2022-03-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0014_order_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishitems',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishitems', to='foodplanapp.dish', verbose_name='Рецепт'),
        ),
    ]
