# Generated by Django 4.0.3 on 2022-03-20 16:46
import random

from django.db import migrations


class Migration(migrations.Migration):
    def set_weight_for_dishes(apps, schema_editor):
        Dish = apps.get_model("foodplanapp", "Dish")

        dishes_set = Dish.objects.all()
        for dish in dishes_set.iterator():
            dish.weight = random.randint(520, 1599)
            dish.save()

    dependencies = [
        ("foodplanapp", "0015_alter_dishitems_dish"),
    ]

    operations = [migrations.RunPython(set_weight_for_dishes)]
