# Generated by Django 4.0.3 on 2022-03-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    def add_price(apps, schema_editor):
        Price = apps.get_model('foodplanapp', 'Price')
        Price.objects.create(
            classic_menu=1000,
            low_calorie_menu=1200,
            vegan_menu=1400,
            keto_menu=1600,
            meal=500,
            new_year_menu=1000,
            allergy=500,
        )

    dependencies = [
        ('foodplanapp', '0017_alter_dish_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(verbose_name='Действует до')),
                ('discount', models.IntegerField(verbose_name='Размер скидки, руб')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.RemoveField(
            model_name='price',
            name='promo_code',
        ),
        migrations.RunPython(add_price),
    ]
