# Generated by Django 4.0.3 on 2022-03-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0018_auto_20220321_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='allergy1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='allergy2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='allergy3',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(null=True, verbose_name='Стоимость подписки'),
        ),
    ]
