# Generated by Django 4.0.3 on 2022-03-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0020_auto_20220321_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'цена', 'verbose_name_plural': 'цены'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='foodplanapp.allergies'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код'),
        ),
    ]
